#!/usr/bin/python3
import pygame;
import os;
import random;
import time;
from yaicadisplay import screen;

disk = input("Enter disk: ");
os.chdir(f"yaicafs/{disk}");
pygame.font.init();
clear = "\033[H\033[2J";
welcome = "Welcome to \033[32mYaicaOS\033[0m";
print(clear+welcome);
print("Loaded ysh");
username = input("Enter username: ");
password = input("Enter password: ");
print(f"Welcome {username}");
while True:
    com = input("> ").split();
    if (not com):
        pass;
    elif (com[0] == "help"):
        f = open("h1.page").read();
        print(f);
    elif (com[0] == "echo"):
        print(' '.join(com[1:]));
    elif (com[0] == "cls"):
        print(clear, end="\r");
    elif (com[0] == "render"):
        screen.fill(0);
        font = pygame.font.Font("ttyfont.ttf", 16);
        jc = ' '.join(com[1:]);
        render = font.render(jc, False, (170,170,170));
        screen.blit(render, (0,0));
        pygame.display.flip();
    elif (com[0] == "scls"):
        screen.fill(0);
        pygame.display.flip();
    elif (com[0] == "yafetch"):
        f = open("yafetch.page").read();
        print(f);
    elif (com[0] == "ls"):
        os.system("dir");
    elif (com[0] == "cd"):
        os.chdir(''.join(com[1:]));
    elif (com[0] == "exit"):
        exit();
    else:
        print("Bad command.");
